application: dynamic-house-86822
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin
- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest


 

