application: meixing-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /rot13
  script: rot13.app
  secure: always

- url: /signup
  script: signup.app
  secure: always
  
- url: /login
  script: signup.app
  secure: always
  
- url: /logout
  script: signup.app
  secure: always
 
- url: /welcome
  script: signup.app
  secure: always
  
- url: /users
  script: signup.app
  secure: always
  
- url: /blog
  script: blog.app
  secure: always
 
- url: /blog/.*
  script: blog.app
  secure: always

- url: /.*
  script: helloworld.app
  
